name: Verify on push

on: [ push ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run ktlint check
        run: ./gradlew ktlintCheck
      - name: Run unit tests
        run: ./gradlew test
